[package]
name = "bridge"
version = "0.1.0"
authors = ["chenej <chenej@gzyitop.com>"]

[dependencies]
error-chain = "0.10"
tokio-core = "0.1"
tokio-io   = "0.1"
futures = "0.1"
serde = "1.0"
toml = "0.4"
